"""empty message

Revision ID: 9fb0c92a3fde
Revises: b4c481707376
Create Date: 2020-05-03 11:44:18.551376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fb0c92a3fde'
down_revision = 'b4c481707376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('featured_article', 'article_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('featured_article', sa.Column('article_title', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=False))
    # ### end Alembic commands ###
