"""empty message

Revision ID: fcec9e4443ca
Revises: d5f247fd4d7f
Create Date: 2020-04-22 22:02:04.057114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcec9e4443ca'
down_revision = 'd5f247fd4d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'publish_time',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'publish_time',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
